version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Run build
          command:  export TERM=${TERM:-dumb} && ./gradlew clean build
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:publish task as the last step in your config.yml file.
-
          paths:
            - ~/.gradlepublish task as the last step in your config.yml file.
-
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
# See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
